### ISSUE TITLE
Query not being send to browser

### ISSUE THREAD

**Issue by aurawindsurfing** [billrobclark/alfred-novadoc-search#1]
Hi!

First of all thanks a lot for all those Alfred plugins, they really did change my workflow! I use your PHP Docs and it works just fine with my Alfred 3 and power pack. The Laravel Nova, however, is not sending query to browser. It serches the docs, shows the results but once you select it and click enter - nothing happens, just the first letter of the query changes itself to capital.

Any ideas what could be an issue here?

Thanks!

<img width="580" alt="screenshot 2018-10-28 12 33 12" src="https://user-images.githubusercontent.com/14302496/47616004-da834200-daae-11e8-838c-b54cbc3be1ca.png">

<img width="586" alt="screenshot 2018-10-28 12 40 02" src="https://user-images.githubusercontent.com/14302496/47616008-df47f600-daae-11e8-8967-49c12c9b9f40.png">

**Comment by techouse** [comment]
I can confirm the same behaviour.

Alfred version v3.7 [938]
macOS: 10.14.1

**Comment by aurawindsurfing** [comment]
nice one @techouse!
